### ISSUE TITLE
Any way for this to apply to gnome.calendar.desktop?

### ISSUE THREAD

**Issue by derek-shnosh** [F-i-f/weeks-start-on-monday#11]
Thank you for the extension! It works great for the calendar that appears when you click the time in the top menu (notifications), but doesn't seem to have any effect on the Calendar (org.gnome.calendar.desktop) application itself.

![image](https://github.com/F-i-f/weeks-start-on-monday/assets/21090563/e09f6c3f-e682-4034-9e9e-73e548ef14f6)

**Comment by derek-shnosh** [comment]
Disregard, I discovered [this](https://askubuntu.com/a/1456874/643965) answer that outlines how to accomplish the "first weekday" issue globally, without modifying other date/time formats.

**Comment by derek-shnosh** [comment]
Disregard, I discovered [this](https://askubuntu.com/a/1456874/643965) answer that outlines how to accomplish the "first weekday" issue globally, without modifying other date/time formats.

**Comment by nekohayo** [comment]
I wish I could help, but Nautilus' codebase complexity is _way_ out of my league (even GNOME Calendar's, in general). I help steer those projects, but it's up to individual contributors to fix what interests them in general.
