### ISSUE TITLE
Change settings using the command line

### ISSUE THREAD

**Issue by AlexZeitler** [F-i-f/weeks-start-on-monday#13]
Thanks for building this extension!

Is there a way to modify the configuration from the command line?

Where are the settings persisted?

**Comment by F-i-f** [comment]
Settings are stored in dconf and can be read and modified with:
```
dconf read /org/gnome/shell/extensions/weeks-start-on-monday/start-day
dconf write /org/gnome/shell/extensions/weeks-start-on-monday/start-day 1
```
This would set the week to start on Monday (=1).

**Comment by AlexZeitler** [comment]
Thanks, it works. Just noticed that `dconf read` doesn't return anything until I set a value using `dconf write`.
