### ISSUE TITLE
Week number should count against Monday, too.

### ISSUE THREAD

**Issue by wangchun** [F-i-f/weeks-start-on-monday#7]
If show week number is enabled, would love to see [ISO week](https://en.wikipedia.org/wiki/ISO_week_date) number is shown. For example today 2022-02-25 should be ISO week 2022-W07, not W08 as shown currently.

**Comment by F-i-f** [comment]
The week number calculations are taking place in Gnome Shell, the extension's purpose is just to shift the first day of the week in the calendar display, and are unrelated.
I'd suggest you file an issue in the [Gnome Shell Gitlab](https://gitlab.gnome.org/GNOME/gnome-shell) instead.
