### ISSUE TITLE
GNOME 44 compatibility

### ISSUE THREAD

**Issue by rickdkk** [F-i-f/weeks-start-on-monday#8]
When running the extension on GNOME 44 I got the following error:

`TypeError: method Gtk.CssProvider.load_from_data: At least 2 arguments required, but only 1 passed`

I added an argument to line 101 of prefs.js, which fixed the compatibility issue:

`css.load_from_data('label { min-width: 12ex; } trough { margin-right: 10ex; }', -1);`

However, I'm not really sure if I understand the docs, so it might break something down the line. Anyways, the extension works for me again. I hope this helps. Thanks a lot for this extension!

**Comment by AkselMeola** [comment]
Any reference to a reason such settings are not in Gnome itself ?

**Comment by hrqmonteiro** [comment]
Opening a PR to just change the version support to 44:

https://github.com/F-i-f/weeks-start-on-monday/pull/9

It's working normally on it.

**Comment by F-i-f** [comment]
Thanks, version 14 has been released today and pushed to the Gnome shell extensions site.
